-- DO NOT EDIT THIS FILE AFTER IT IS PUSHED IT WILL DIVERGE THE DATABASE
-- IF YOU WANT TO EDIT THE YOU HAVE TO ADD A SEPARATE V2__add_something.sql file

USE customerdb;

-- Indexes are declared inline rather than as separate CREATE INDEX statements:
-- MySQL 8 has no CREATE INDEX IF NOT EXISTS, so keeping them inside the table
-- definition is what makes this whole migration safe to re-run.
CREATE TABLE IF NOT EXISTS customers (
    id                  CHAR(36)     NOT NULL,
    name                VARCHAR(100) NOT NULL,
    phone               VARCHAR(20)  NOT NULL,
    phone_normalized    VARCHAR(20)  NOT NULL,
    phone_active_unique VARCHAR(20)  GENERATED ALWAYS AS (IF(status = 'ACTIVE', phone_normalized, NULL)) STORED,
    address             VARCHAR(255) NOT NULL,
    customer_type       VARCHAR(20)  NOT NULL,
    email               VARCHAR(255) NULL,
    status              VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    UNIQUE KEY uq_customers_phone_active (phone_active_unique),
    KEY idx_customers_status (status),

    CONSTRAINT chk_customers_customer_type CHECK (customer_type IN ('INDIVIDUAL', 'BUSINESS')),
    CONSTRAINT chk_customers_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);
