-- DO NOT EDIT THIS FILE AFTER IT IS PUSHED IT WILL DIVERGE THE DATABASE
-- IF YOU WANT TO EDIT THE YOU HAVE TO ADD A SEPARATE V3__add_something.sql file

USE customerdb;

-- Indexes are declared inline rather than as separate CREATE INDEX statements:
-- MySQL 8 has no CREATE INDEX IF NOT EXISTS, so keeping them inside the table
-- definition is what makes this whole migration safe to re-run.
CREATE TABLE IF NOT EXISTS assets (
    id                CHAR(36)     NOT NULL,
    customer_id       CHAR(36)     NOT NULL,
    asset_type        VARCHAR(20)  NOT NULL,
    model             VARCHAR(100) NOT NULL,
    serial_number     VARCHAR(100) NOT NULL,
    serial_normalized VARCHAR(100) NOT NULL,
    installation_date DATE         NOT NULL,
    location          VARCHAR(255) NOT NULL,
    notes             VARCHAR(1000) NULL,
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    -- A serial number identifies one physical unit, so it is unique across the
    -- whole table, not per customer. Unlike the customers table there is no
    -- status here to scope it by - an asset row is never retired in place.
    UNIQUE KEY uq_assets_serial_normalized (serial_normalized),
    -- Listing a customer's assets is the query this table exists for.
    KEY idx_assets_customer_id (customer_id),

    CONSTRAINT chk_assets_asset_type CHECK (asset_type IN ('AIR_CONDITIONER', 'REFRIGERATOR', 'WASHING_MACHINE', 'WATER_HEATER', 'OTHER')),

    -- RESTRICT, not CASCADE: deleting a customer that still owns assets is a
    -- mistake to surface, not a reason to silently destroy their equipment
    -- history. Customers are deactivated rather than deleted anyway.
    CONSTRAINT fk_assets_customer FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE RESTRICT
);
