-- DO NOT EDIT THIS FILE AFTER IT IS PUSHED IT WILL DIVERGE THE DATABASE
-- IF YOU WANT TO EDIT THE YOU HAVE TO ADD A SEPARATE V4__add_something.sql file

USE customerdb;

-- Unlike V01 and V02 this migration is not safe to re-run: MySQL 8 has no
-- ALTER TABLE ... ADD COLUMN IF NOT EXISTS - that is MariaDB syntax - so a
-- second run would fail with "Duplicate column name 'status'". What makes that
-- acceptable is apply_migrations.ps1 recording applied filenames in
-- schema_migrations and skipping them, so this file is applied exactly once.
ALTER TABLE assets
    -- Mirrors customers.status: same type, same default, same two values.
    -- Existing rows take the default and come out ACTIVE, which is what they
    -- were before the column existed.
    ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' AFTER notes,
    -- V02 said an asset row is never retired in place. It is now - but the
    -- unique index on serial_normalized is still not scoped by status, unlike
    -- the customers table's phone_active_unique. A deactivated asset is a
    -- physical unit that still exists, so its serial stays taken.
    ADD CONSTRAINT chk_assets_status CHECK (status IN ('ACTIVE', 'INACTIVE')),
    -- Listing only the live assets is the query this index exists for.
    ADD KEY idx_assets_status (status);
